from utils import *

# specify the column_builder_parameters here
# make sure you pass the correct arguments for
# any custom function in the last element of the
# tuple
pipe_params = [
    ('2.1', 'TeamAvg', None, None),
    ('2.1', 'ClassAvg', None, None),
    ('2.1', 'ClassStDev', None, None),
    ('2.2', 'TeamAvg', None, None),
    ('2.3', 'TeamAvg', None, None),
    ('4.1', 'TeamAvg', None, None),
    ('4.1', 'ClassAvg', None, None),
    ('4.1', 'ClassStDev', None, None),
    ('4.2', 'TeamAvg', None, None),
    ('4.2', 'ClassAvg', None, None),
    ('4.2', 'ClassStDev', None, None),
    ('4.3', 'TeamAvg', None, None),
    ('4.3', 'ClassAvg', None, None),
    ('4.3', 'ClassStDev', None, None),
    ('4.4', 'TeamAvg', None, None),
    ('4.4', 'ClassAvg', None, None),
    ('4.4', 'ClassStDev', None, None),
    ('5', 'Me', get_my_response, ['5']),
    ('5', 'TeammateAvg', None, None),
    ('6', 'Me', None, None),
    ('7', 'Me', None, None),
    ('14', 'Me', get_my_response, ['14']),
    ('14', 'PerMember', None, ['14']),
    # ('15', 'Me', get_my_response, ['15']),
    # ('15', 'PerMember', None, ['15']),
    ('16', 'Me', get_my_response, ['16']),
    ('16', 'TeammateAvg', None, None),
    ('16', 'ClassAvg', get_class_average_all_teammates, ['16']),
    ('16', 'ClassStDev', get_class_stdev_all_teammates, ['16']),
    ('17', 'Me', get_my_response, ['17']),
    ('17', 'TeammateAvg', None, None),
    ('17', 'ClassAvg', get_class_average_all_teammates, ['17']),
    ('17', 'ClassStDev', get_class_stdev_all_teammates, ['17']),
    ('18', 'Me', get_my_response, ['18']),
    ('18', 'TeammateAvg', None, None),
    ('18', 'ClassAvg', get_class_average_all_teammates, ['18']),
    ('18', 'ClassStDev', get_class_stdev_all_teammates, ['18']),
    ('19', 'Me', get_my_response, ['19']),
    ('19', 'TeammateAvg', None, None),
    ('19', 'ClassAvg', get_class_average_all_teammates, ['19']),
    ('19', 'ClassStDev', get_class_stdev_all_teammates, ['19']),
]
